"""empty message

Revision ID: 1ff61054384e
Revises: 661844321e18
Create Date: 2023-03-09 15:42:38.851363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ff61054384e'
down_revision = '661844321e18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bedrooms', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('bathrooms', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('photo', sa.String(length=100), nullable=False))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_profiles', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('photo')
        batch_op.drop_column('type')
        batch_op.drop_column('location')
        batch_op.drop_column('bathrooms')
        batch_op.drop_column('bedrooms')

    # ### end Alembic commands ###
