"""empty message

Revision ID: 3e6e6dfa8f3f
Revises: 1ff61054384e
Create Date: 2023-03-10 18:31:33.776214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e6e6dfa8f3f'
down_revision = '1ff61054384e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_type', sa.String(length=20), nullable=False))
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_column('property_type')

    # ### end Alembic commands ###
